### ISSUE TITLE
Output is just a Hello World!

### ISSUE THREAD

**Issue by anishd19** [nginformatica/mern-todo#4]
I am getting nothing more than a Hello World! in the browser.

**Comment by cuchi** [comment]
Hi! Thanks for the interest :)

The root route displays just a `Hello World`, this is right.

The available pages of this project are `/login` and `/tasks`, as you can see in the [index.jsx file](https://github.com/nginformatica/mern-todo/blob/master/client/Index.jsx).

We are still planning to build a user creation page, so that means you will need to manually create a user with a mongodb CLI/GUI client if you want to see it working nicely.

This demo project is under (kind of) inactive development and it is outdated already, but we intend to update it to use the latest features of the stack.
